-- Turso / libSQL seed for the universities table
-- Run this once after creating your Turso database.

DROP TABLE IF EXISTS universities;

CREATE TABLE universities (
  id INTEGER PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  postdoc_r INTEGER DEFAULT 0,
  postdoc_allocated INTEGER DEFAULT 0,
  postdoc_disbursed INTEGER DEFAULT 0,
  postdoc_launched INTEGER DEFAULT 0,
  postdoc_status TEXT DEFAULT '',
  infra_allocated INTEGER DEFAULT 0,
  infra_disbursed INTEGER DEFAULT 0,
  infra_status TEXT DEFAULT '',
  hqr_allocated INTEGER DEFAULT 0,
  hqr_disbursed INTEGER DEFAULT 0,
  hqr_status TEXT DEFAULT '',
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Seed data (48 universities)
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (1,'جامعة الملك عبدالعزيز','King AbdulAziz University',16,3970000,1872000,16,'مشارك',7849796,0,'مشارك',3998994,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (2,'جامعة الملك سعود','King Saud University',20,4930000,2400000,20,'مشارك',7459543,0,'مشارك',3998994,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (3,'جامعة الملك فهد للبترول والمعادن','King Fahd University of Petroleum & Minerals',15,3730000,144000,2,'مشارك',3920004,0,'مشارك',2000073,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (4,'جامعة الملك فيصل','King Faisal University',5,1240000,504000,5,'مشارك',1960004,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (5,'جامعة الملك خالد','King Khalid University',0,0,0,0,'لم يتأهل',1960000,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (6,'جامعة أم القرى','Umm AlQura University',6,1480000,720000,6,'مشارك',1960000,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (7,'جامعة الطائف','Taif University',5,1240000,600000,5,'مشارك',1951173,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (8,'جامعة القصيم','Qassim University',5,1240000,480000,4,'مشارك',1960000,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (9,'جامعة شقراء','Shaqra University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (10,'جامعة المجمعة','Majmaah University',0,0,0,0,'لم يشارك',489509,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (11,'جامعة الحدود الشمالية','Northern Border University',0,0,0,0,'لم يتأهل',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (12,'جامعة حفر الباطن','Hafr AlBatin University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (13,'جامعة حائل','Hail University',0,0,0,0,'لم يشارك',489999,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (14,'جامعة جازان','Jazan University',0,0,0,0,'لم يشارك',491120,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (15,'جامعة نجران','Najran University',6,1480000,600000,5,'مشارك',501540,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (16,'جامعة طيبة','Taibah University',8,1995000,0,0,'مشارك',1960000,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (17,'جامعة الإمام محمد بن سعود الإسلامية','Imam Mohammed Ibn Saud Islamic University',5,1240000,336000,3,'مشارك',490003,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (18,'جامعة الإمام عبدالرحمن بن فيصل','Imam AbdulRahman Bin Faisal University',0,0,0,0,'لم يتأهل',1960004,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (19,'جامعة بيشة','University of Bisha',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (20,'جامعة الباحة','AlBaha University',0,0,0,0,'لم يتأهل',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (21,'الجامعة السعودية الإلكترونية','Saudi Electronic University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (22,'جامعة الأمير سطام بن عبدالعزيز','Prince Sattam Bin AbdulAziz University',0,0,0,0,'لم يتأهل',489999,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (23,'جامعة الأميرة نورة بنت عبدالرحمن','Princess Nourah Bint AbdulRahman University',0,0,0,0,'لم يتأهل',490003,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (24,'جامعة جدة','University of Jeddah',0,0,0,0,'لم يتأهل',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (25,'جامعة تبوك','Tabuk University',0,0,0,0,'لم يتأهل',1960000,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (26,'جامعة الجوف','AlJouf University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (27,'جامعة الملك سعود بن عبدالعزيز للعلوم الصحية','KSAU Health Sciences',9,2235000,1080000,9,'مشارك',1932063,0,'مشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (28,'جامعة الملك عبدالله للعلوم والتقنية','KAUST',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (29,'الجامعة الإسلامية','Islamic University of Madina',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (30,'جامعة الأمير سلطان','Prince Sultan University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (31,'مركز الملك عبدالله العالمي للبحوث الطبية','King Abdullah International Medical Research Center',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (32,'جامعة عفت','Effat University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (33,'كلية الملك فهد الأمنية','King Fahd Security College',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (34,'كليات سليمان الراجحي','Sulaiman Al Rajhi Colleges',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (35,'كلية ينبع الجامعية','Yanbu University College',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (36,'الجامعة العربية المفتوحة','Arab Open University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (37,'جامعة دار العلوم','Dar Al Uloom University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (38,'جامعة الفيصل','Al-Faisal University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (39,'كلية ينبع الصناعية','Yanbu Industrial College',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (40,'كلية القصيم الخاصة','Qassim Private Colleges',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (41,'جامعة الأمير مقرن','Prince Mugrin University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (42,'كلية الجبيل الجامعية','Jubail University College',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (43,'جامعة الأمير محمد بن فهد','Prince Mohammad bin Fahd University',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (44,'المؤسسة العامة للتدريب التقني والمهني','TVTC',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (45,'مدينة الملك عبدالعزيز للعلوم والتقنية','KACST',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (46,'جامعة العلوم والتكنولوجيا','University of Business and Technology',0,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (47,'كلية الريان للعلوم الطبية','Al Rayan Medical Colleges',1,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
INSERT INTO universities (id,name_ar,name_en,postdoc_r,postdoc_allocated,postdoc_disbursed,postdoc_launched,postdoc_status,infra_allocated,infra_disbursed,infra_status,hqr_allocated,hqr_disbursed,hqr_status) VALUES (48,'جامعة علم الرياض','Riyadh Elm University',2,0,0,0,'لم يشارك',0,0,'لم يشارك',0,0,'لم يشارك');
